### ISSUE TITLE
PullRequests' Diff And DiffStat calls always return 403

### ISSUE THREAD

**Issue by iremezoff** [lvermeulen/Bitbucket.Cloud.Net#14]
I've checked why it occurs and come across that authorization header never goes to bitbucket api. I used basic/app/oauth authentication options. I also checked that oauth token is valid and works well with straightforward requests through Postman but in exception details returning with 403 response no auth header is included.

Btw, the GetRepositoryPullRequestAsync works perfectly as expected.

**Comment by lvermeulen** [comment]
Can you send a PR?
