### ISSUE TITLE
using GetRepositoryPullRequestCommitsAsync, I only ever get 10 results back e

### ISSUE THREAD

**Issue by twilly86** [lvermeulen/Bitbucket.Cloud.Net#16]
Using the following request..

                var commits = await _client.GetRepositoryPullRequestCommitsAsync(workspaceId, repositorySlug, pullRequest.Id.ToString(), maxPages: 30);

I only ever get 10 results back, it looks like paging is not working.

**Comment by twilly86** [comment]
response is coming back with next in the following format versus an ID which is incremented in base paging..

pullrequests/1138/commits?page=dbtR"

**Comment by lvermeulen** [comment]
@gjhommersom might be making a pull request for this
