### ISSUE TITLE
Paging for GetRepositoryCommitsAsync does not seem to work

### ISSUE THREAD

**Issue by BjartN** [lvermeulen/Bitbucket.Cloud.Net#2]
The call await client.GetRepositoryCommitsAsync(workspace, repoSlug, 20) gives the same page 20 times. (I am using the version 1.0.0 Nuget package)

**Comment by lvermeulen** [comment]
Do you have a repository on which I can reproduce this?

**Comment by BjartN** [comment]
This piece of code seems to be iterating over "numPages" without ever using the value of it. I'm assuming this is the problem.

`
private async Task<IEnumerable<T>> GetPagedResultsAsync<T>(int? maxPages, IDictionary<string, object> queryParamValues, Func<IDictionary<string, object>, Task<PagedResults<T>>> selector)
		{
			var results = new List<T>();
			bool isLastPage = false;
			int numPages = 0;

			while (!isLastPage && (maxPages == null || numPages < maxPages))
			{
				var selectorResults = await selector(queryParamValues).ConfigureAwait(false);
				results.AddRange(selectorResults.Values);

				isLastPage = selectorResults.Next == null;
				numPages++;
			}

			return results;
		}
`

**Comment by lvermeulen** [comment]
Found it! :-) It was actually a little bit more involved than that, have a look at GetPagedResultsAsync(). The devil is in the Math.Max details. Thanks for reporting this issue!
