### ISSUE TITLE
View pull request by commit hash

### ISSUE THREAD

**Issue by psych001x** [lvermeulen/Bitbucket.Cloud.Net#3]
I am trying to get the details of a merged pull request based on a commit hash. I think the method GetRepositoryCommitPullRequestsAsync is what I'm after, but I get an exception saying the URL doesn't exist. 

I've updated the unit test GetRepositoryCommitPullRequestsAsync to be a repository I have permissions to (luve / test doesn't work) and I see the same exception. Are you able to provide an example which works?

**Comment by lvermeulen** [comment]
I believe the method you're after is the right one. And the example in my unit test works:
* Create a repository
* Perform a commit
* Create a pull request from this commit

However, if you're getting an exception saying that the URL doesn't exist, then I would double-check if you do in fact have the correct URL. The URL should always be https://api.bitbucket.org, and you can use your username/password to log in.

If you give me access to your repository, I can try it for you.
