### ISSUE TITLE
Failed to parse Json

### ISSUE THREAD

**Issue by Xcone** [lvermeulen/Bitbucket.Cloud.Net#8]
Hi, 

When a repository is quite large, querying a workspace for repositories (`client.GetWorkspaceRepositoriesAsync`) fails.

`{"JSON integer 11289926597 is too large or small for an Int32. Path 'values[0].size', line 1, position 2913."}`

It seems to point to this line. I think if you make it a long instead of int, it should be good already. But I'll let you be the judge on that :-) :
https://github.com/lvermeulen/Bitbucket.Cloud.Net/blob/9796870f4bae83a6ca2f724f0af0e599696c14d8/src/Bitbucket.Cloud.Net/Models/v2/Repository.cs#L36

**Comment by lvermeulen** [comment]
Thanks, @Xcone  - fixed.
