### ISSUE TITLE
CreateRepositoryPullRequestAsync failed because of status code 400

### ISSUE THREAD

**Issue by woodylic** [lvermeulen/Bitbucket.Cloud.Net#9]
Code:

```csharp
var pr = await client.CreateRepositoryPullRequestAsync(workspaceId, repositorySlug,
        new PullRequestCreationParameters
        {
            Title = $"Auto-merge for release {version} completion.",
            Source = new HasName { Name = releaseBranch },
            Destination = new HasName { Name = "develop" }
        }).ConfigureAwait(false);
```

Error:

Unhandled exception. Flurl.Http.FlurlHttpException: Call failed with status code 400 (Bad Request): POST https://api.bitbucket.org/2.0/repositories/english1/auth2/pullrequests

According to the API document ([link](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/pullrequests#post)), the expected request body is

```json
{
    "title": "My Title",
    "source": {
        "branch": {
            "name": "my-feature-branch"
        }
    },
    "destination": {
        "branch": {
            "name": "staging"
        }
    }
}
```

The actual request body is

```json
{
  "title": "My Title",
  "source": {
    "name": "my-feature-branch"
  },
  "destination": {
    "name": "staging"
  }
}
```

Furthermore, PullRequestCreationParameters requests Reviewer but it is not used when sending the REST request.

**Comment by lvermeulen** [comment]
Thanks for reporting this, @woodylic ! Fix is in the next release.
